// ** component
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

// ** assets
import "@/assets/styles/globals.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Navbar></Navbar>
        <div>{children}</div>
        <Footer></Footer>
      </body>
    </html>
  );
}
